TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'PHLU.Neos.NodeTypes': TRUE

    userInterface:
      translation:
        autoInclude:
          'PHLU.Neos.NodeTypes': ['NodeTypes/*']


  TYPO3CR:
    contentDimensions:
      'language':
        label: 'Sprache'
        icon: 'icon-language'
        default: 'de'
        defaultPreset: 'de'
        presets:
          'all': ~
          'de':
            label: 'Deutsch'
            values: ['de']
            uriSegment: ''
          'fr':
            label: 'Français'
            values: ['fr']
            uriSegment: 'fr'
          'it':
            label: 'Italiano'
            values: ['it']
            uriSegment: 'it'
