
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Phlu.Neos.NodeTypes:
            - 'NodeTypes/*'
      requireJsPathMapping:
        Phlu.Neos.NodeTypes/Handlers: 'resource://Phlu.Neos.NodeTypes/Public/JavaScript/Backend/Inspector/Handlers'
    fusion:
      autoInclude:
        Phlu.Neos.NodeTypes: true
  ContentRepository:
    contentDimensions:
      language:
        label: Sprache
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          all: null
          de:
            label: Deutsch
            values:
              - de
            uriSegment: ''
          fr:
            label: Français
            values:
              - fr
            uriSegment: fr
          it:
            label: Italiano
            values:
              - it
            uriSegment: it