
TYPO3:
  TYPO3CR:
    contentDimensions:
      language:
        label: Sprache
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          all: null
          de:
            label: Deutsch
            values:
              - de
            uriSegment: ''
          fr:
            label: Français
            values:
              - fr
            uriSegment: fr
          it:
            label: Italiano
            values:
              - it
            uriSegment: it
Neos:
  Neos:
    typoScript:
      autoInclude:
        PHLU.Neos.NodeTypes: true
    userInterface:
      translation:
        autoInclude:
          PHLU.Neos.NodeTypes:
            - 'NodeTypes/*'
